name: Build/release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build static files
        run: npm run build --if-present
      - name: Build/release Electron app ${{ matrix.os }}
        run: npm run make
